version: 0.0
os: linux

files:
  - source: ./shall-we-meet-then-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 60
      runas: ubuntu

  ApplicationStop:
    - location: scripts/docker_stop.sh
      timeout: 60
      runas: ubuntu